default:  fxctmp9_tmp\voxels_vs20.inc shaders\fxc\voxels_vs20.vcs fxctmp9_tmp\voxels_ps20.inc shaders\fxc\voxels_ps20.vcs

fxctmp9_tmp\voxels_vs20.inc shaders\fxc\voxels_vs20.vcs: voxels_vs20.fxc 
	perl perl\fxc_prep.pl   -source "." voxels_vs20.fxc-----voxels_vs20
	echo voxels_vs20.fxc>> filestocopy.txt

fxctmp9_tmp\voxels_ps20.inc shaders\fxc\voxels_ps20.vcs: voxels_ps20.fxc 
	perl perl\fxc_prep.pl   -source "." voxels_ps20.fxc-----voxels_ps20
	echo voxels_ps20.fxc>> filestocopy.txt

